config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"

  resources :experiences do
    member do
      get 'overview'
      get 'description'
      get 'settings'
      get 'contact'
      get 'photos'
    end
  end

  resources :users, only: [:show]

  get 'users/show'
  get 'experiences/show'
  get 'experiences/index'
  get 'my_experiences', to: 'pages#my_experiences'

  # Static pages
  get 'about', to: 'pages#about'
  get 'blog', to: 'pages#blog'
  get 'career', to: 'pages#career'
  get 'credits', to: 'pages#credits'
  get 'faq', to: 'pages#faq'
  get 'host', to: 'pages#host'
  get 'standards', to: 'pages#standards'
  get 'why_hosting', to: 'pages#why_hosting'
  get 'account', to: 'pages#account'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/experience.rb
class Experience < ApplicationRecord
  enum status: { Draft: 0, Pending: 1, Active: 2, Inactive:3, Rejected: 4 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user

  has_one_attached :cover
  has_many_attached :photos


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :experiences

  has_one_attached :avatar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def authenticate_admin
    redirect_to '/', alert: 'Not authorized.' unless current_user && access?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar, :description, :email])
  end

  def access?
    current_user.admin? == true
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]

  def show
  end

  def index
    @experiences = nil
    if params[:query].present?
      query_params = params[:query]
      @experiences = Experience.near(query_params, 1)
    else
      @experiences = Experience.all
    end
      # The `geocoded` scope filters only experiences with coordinates
      @experiences = @experiences.geocoded
      @markers = @experiences.map do |experience|
        {
          lat: experience.latitude,
          lng: experience.longitude
        }
      end
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    if @experience.valid?
      @experience.save
      redirect_to overview_experience_path(@experience), notice: "New experience created !"
    else
      render :new, notice: "Oops, something went wrong while creating your experience."
    end
  end

  def edit
    render :new
  end

  def update
    if @experience.update(experience_params)
      flash[:notice] = "Saved..."

    else
      flash[:alert] = "Oops, something went wrong ..."
    end
    redirect_back(fallback_location: request.referer)
  end

  def destroy
    @experience.destroy
    flash[:notice] = "Your experience has been deleted"
    redirect_to my_experiences_path, status: :see_other
  end

  def overview
  end

  def description
  end

  def settings
  end

  def contact
  end

  def photos
    @photos = @experience.photos
  end

  def delete_cover_attachment
    @cover_url = ActiveStorage::Attachment.find(params[:id])
    @cover_url.purge
    redirect_back(fallback_location: request.referer)
  end


  private

  def to_submit?
    !@accommodation.description.blank? && !@accommodation.price.blank? && !@accommodation.address.blank? ? true : false
  end

  def set_experience
    @experience = Experience.find(params[:id])
  end

  def experience_params
    params.require(:experience).permit(:name,
                                        :description,
                                        :exp_type,
                                        :address,
                                        :website,
                                        :exp_phone,
                                        :max_capacity,
                                        :status,
                                        :latitude,
                                        :longitude,
                                        :cover,
                                        photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :host ]

  def home
  end

  def host
  end

  def about

  end

  def blog

  end

  def career

  end

  def why_hosting

  end

  def standards

  end

  def faq

  end

  def credits

  end

  def account
    @user = current_user
  end

  def my_experiences
    @experiences = current_user.experiences
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_user, only: [:show, :destroy]


  def show
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
    return File.read(file_path).html_safe if File.exists?(file_path)
    '(not found)'
  end

  def avatar_for(user)
    "https://res.cloudinary.com/myntee/image/upload/v1596748062/default_user_avatar_w78auz.png"
  end
end

app/views/experiences/_photos_grid.html.erb
<div class="container-grid-photos">


<div class="grid product">
  <div class="product-gallery">
    <div class="row">
      <div class="col-md-8 p-0">
        <div class="product-image">
          <%= cl_image_tag(experience.photos[0].key, {class: "active"}) %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="photos-grid image-list">
          <% @experience.photos.each do |photo| %>
          <% if !photo.nil? %>
            <div class="image-item">
              <%= cl_image_tag photo.key %>
            </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<script>
  const activeImage = document.querySelector(".product-image .active");
  const productImages = document.querySelectorAll(".image-list img");
  const navItem = document.querySelector('a.toggle-nav');

  function changeImage(e) {
    activeImage.src = e.target.src;
  }

  function toggleNavigation(){
    this.nextElementSibling.classList.toggle('active');
  }

  productImages.forEach(image => image.addEventListener("click", changeImage));
  navItem.addEventListener('click', toggleNavigation);

</script>

app/views/experiences/contact.html.erb
<div class="row">
  <div class="col-2">
    <%= render "shared/onboarding_side_nav" %>
  </div>
  <div class="col-10">
    <div class="onboarding-box">
      <h1>Where can we contact you</h1>
      <br>
        <%= simple_form_for @experience do |f| %>
          <%= f.error_notification %>
          <h3>Where can your clients contact you:</h3>
          <%= f.input :exp_phone, label: false, hint: "Use the international format +44 XXXX XXXXXX", class: "form-control" %>
          <br>

          <h3>Do you have a website to take bookings ?</h3>
          <%= f.input :website, label: false, hint: "Example: https://www.treepr.co.uk", class: "form-control" %>
          <br>


          <%= f.submit "Save", class: "btn btn-flat" %>
        <% end -%>

    </div>
  </div>
</div>

app/views/experiences/description.html.erb
<div class="row">
  <div class="col-2">
    <%= render "shared/onboarding_side_nav" %>
  </div>
  <div class="col-10">
    <div class="onboarding-box">
      <h1>What kind of experience do you host ?</h1>
      <br>
        <%= simple_form_for @experience do |f| %>
          <%= f.error_notification %>
          <h3>Describe your experience: </h3>
          <%= f.input :description, as: :text, label: "Describe with your own words the kind of experience you would like to offer.", hint: "maximum 1000 characters", class: "form-control" %>
          <br>

          <P>Add Nature features (Multiple selector)</P>


          <%= f.submit "Save", class: "btn btn-flat" %>
        <% end -%>

    </div>
  </div>
</div>

app/views/experiences/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6">
      <div class="cards">
        <% if @experiences.length > 0 %>
          <% @experiences.each do |experience| %>
            <%= link_to experience_path(experience) do %>
              <%= render 'shared/experience_card', experience: experience %>
            <% end -%>
          <% end %>
        <% else %>
        <p>Sorry, we couldn't find any campsites that match your search. Please try again</p>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <div style="width: 100%; height: 600px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>

    </div>
  </div>
</div>

app/views/experiences/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <h1>Register your experience</h1>
    <br>
    <div class="col-xs-12 col-md-6">
      <%= simple_form_for @experience do |f| %>


        <div class="form-group">
          <label>Your experience name</label>
          <%= f.text_field :name, label: "Experience Name", autocomplete: 'off', class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.input :address, placeholder: "Enter your precise address", hint: "Campers will only get your exact address once they’ve booked a reservation.", class: "form-control" %>
        </div>
        <br>

        <br>
        <div class="container text-center">
            <%= f.button :submit,"Host Now", class: "btn btn-ghost" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/experiences/overview.html.erb
<div class="row">
  <div class="col-2">
    <%= render "shared/onboarding_side_nav" %>
  </div>
  <div class="col-10">
    <div class="onboarding-box">
      <h1>Create your experience<span style="color: #E67E22">.</span></h1>
      <div class="dropdown-divider orange"></div><br>
      <br>
        <%= simple_form_for @experience do |f| %>
          <%= f.error_notification %>
          <h3>Select the type of experience you offer</h3>
          <%= f.input :exp_type, collection: [["Glamping", "Glamping"],["Bring Your Own tent", "Bring Your Own tent"],["Campsite", "Campsite"], ["RV Park", "RV Park"], ["Camping", "Camping"]], label: false, class: "form-control" %>
          <br>

          <h3>What is your experience name</h3>
          <%= f.text_field :name, label: "Experience Name", autocomplete: 'off', class: "form-control", hint:"Chose a vibrant name" %>
          <br>

          <h3>Where is your experience located</h3>

          <%= f.input :address, placeholder: "Enter your precise address", hint: "Example: Nelson road, London, W1 1A0", class: "form-control" %>


          <%= f.submit "Save", class: "btn btn-flat" %>
        <% end -%>

    </div>
  </div>
</div>

app/views/experiences/settings.html.erb
<div class="row">
  <div class="col-2">
    <%= render "shared/onboarding_side_nav" %>
  </div>
  <div class="col-10">
    <div class="onboarding-box">
      <h1>What kind of experience do you host ?</h1>
      <br>
      <p>To be added on the form and db:</p>
      <ul>
        <li>Amenities</li>
        <li>Pricing</li>
        <li>Group</li>      </ul>

    </div>
  </div>
</div>

app/views/pages/about.html.erb
.about.html.erb

app/views/pages/account.html.erb
<div class="container content">
  <div class="row d-flex justify-content-center p-3">
    <div class="col-xs-12 w-100">

      <h3><strong>Account<span style="color: #E67E22">.</span></strong></h3>
      <br>
      <h3><%= @user.first_name + " " + @user.last_name %></h3>
      <p><%= @user.email %>
      </p>
      <br>

      <div class="container">
          <div class="card-grid">
            <div class="card-setting green myBox">
              <%= link_to my_experiences_path(@user) do %>
                <%= svg "icon-dashboard" %>
                <h4 class="orange">Host Management Tools > </h4>
                <p>Manage your campsites listing, your reservations & host calendars</p>
              <% end %>
            </div>
            <div class="card-setting green myBox">
              <%= link_to host_path do %>
                <%= svg "icon-notification" %>
                <h4 class="orange">Notifications > </h4>
                <p>Choose notifications preferences</p>
              <% end %>
            </div>
            <div class="card-setting green myBox">
              <%= link_to host_path do %>
                <%= svg "icon-payment" %>
                <h4 class="orange">Payments & payouts > </h4>
                <p>Manage your saved payment details and setup your hosting payouts</p>
              <% end %>
            </div>
            <div class="card-setting green">
              <%= svg "icon-referral" %>
              <h4 class="orange">Invite your friends > </h4>
              <p>Manage your campsites</p>
              <span class="badge badge-pill badge-primary">Coming soon</span>
            </div>
          </div>
      </div>
      <br>

      <div class="container">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-ghost" %>
      </div>
      <br>

    </div>
  </div>
</div>

<script>
  $(".myBox").click(function() {
  window.location = $(this).find("a").attr("href");
  return false;
});
</script>

app/views/pages/blog.html.erb
blog.html.erb

app/views/pages/career.html.erb
<p>to file</p>

app/views/pages/credits.html.erb
<p>Host Image by <a href="https://www.freepik.com/free-vector/adventure-lettering-with-photo_4581272.htm#query=camping&position=16&from_view=search&track=sph">Freepik</a></p>

app/views/pages/faq.html.erb
<p>to file</p>

app/views/pages/home.html.erb
<header class="home bg-hero">
  <div class="container">

    <div class="hero-title text-center">
      <h1>Live your next adventure <span style="color: #0E343A">Outdoor</span><span style="color: #E67E22">.</span></h1>
      <p>
      Search, discover and enjoy all kind of unique outdoor experiences from a single platform<br>
      From experiencing outdoor stays to daily activites <br>
      Spend less time searching, more time enjoying outdoor adventures<span style="color: #E67E22">.</span>
      </p>
    </div>

    <div class="col-xs-12 w-100">

      <%= form_with url: experiences_path, method: :get, class: "search-form-control d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find an experience"
        %>
        <%= submit_tag "Search", class: "btn btn-flat" %>
      <% end %>
    </div>

  </div>
</header>

<div class="home-section">
  <div class="container">
    <div class="row justify-content-center mb-5">
      <div class="col-lg-6 text-center">
        <h2 class="section-title text-center mb-3">Our Services</h2>
        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
      </div>
    </div>

      <div class="row align-items-stretch">
        <div class="col-lg-4 order-lg-1">
          <div class="h-100"><div class="frame h-100"><div class="feature-img-bg h-100"></div></div></div>
        </div>

        <div class="col-6 col-sm-6 col-lg-4 feature-1-wrap d-md-flex flex-md-column order-lg-1" >

          <div class="feature-1 d-md-flex">
            <div class="align-self-center">
              <span class="flaticon-house display-4 text-primary"></span>
              <h3>Beautiful Condo</h3>
              <p class="mb-0">Even the all-powerful Pointing has no control about the blind texts.</p>
            </div>
          </div>

          <div class="feature-1 ">
            <div class="align-self-center">
              <span class="flaticon-restaurant display-4 text-primary"></span>
              <h3>Restaurants & Cafe</h3>
              <p class="mb-0">Even the all-powerful Pointing has no control about the blind texts.</p>
            </div>
          </div>

        </div>

        <div class="col-6 col-sm-6 col-lg-4 feature-1-wrap d-md-flex flex-md-column order-lg-3" >

          <div class="feature-1 d-md-flex">
            <div class="align-self-center">
              <span class="flaticon-mail display-4 text-primary"></span>
              <h3>Easy to Connect</h3>
              <p class="mb-0">Even the all-powerful Pointing has no control about the blind texts.</p>
            </div>
          </div>

          <div class="feature-1 d-md-flex">
            <div class="align-self-center">
              <span class="flaticon-phone-call display-4 text-primary"></span>
              <h3>24/7 Support</h3>
              <p class="mb-0">Even the all-powerful Pointing has no control about the blind texts.</p>
            </div>
          </div>

        </div>

      </div>
  </div>
</div>


<section class="border-top" id="defaultProcess">
  <div class="container">
    <div class="row justify-content-center text-center mb-6">
      <div class="col-lg-6">
        <h2 class="fs-3 fs-sm-4 text-decoration-underline mb-3">our process</h2>
        <p class="text-500 fst-italic">Our process is a flexible framework that adapts, evolves and responds to your needs. It is the streamlined result of two decades of website design and marketing for hundreds of clients.</p>
        <hr class="hr-short mt-5">
      </div>
    </div>
    <div class="row">
      <div class="col-12 ps-lg-7">
        <div class="row align-items-end">
          <div class="col-lg-6 order-lg-2 text-center"><img class="img-fluid" src="../assets/img/illustration/process-01.svg" alt="" width="400"></div>
          <div class="col-lg-6 border-lg-start border-lg-bottom pb-lg-8 mt-4 mt-lg-0 mb-8 mb-lg-0">
            <div class="process-item ms-6 ms-sm-8 ms-lg-6"><span class="process-item-number">01</span>
              <h3>plan</h3>
              <p>We set priorities, organize content, and understand the buyer’s journey that your audience takes as they navigate your website. At the end of strategy, you will have a Blueprint for your website project, a comprehensive strategic plan for your website design, content, and functionality.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6 border-lg-end border-lg-bottom text-center py-lg-8"><img class="img-fluid" src="../assets/img/illustration/process-02.svg" alt="" width="400"></div>
          <div class="col-lg-6 mt-4 mb-8 my-lg-8">
            <div class="process-item ms-6 ms-sm-8 ms-lg-6"><span class="process-item-number">02</span>
              <h3>design</h3>
              <p>Once the Blueprint is approved, we create wireframes and a design comp for your review. This process involves various reviews, approvals, and close communication between you and our creative team. We begin with the Homepage to set style, image and branding standards, then move toward interior layouts.</p><a class="btn btn-outline-dark btn-sm mt-3" href="#!">View Methods</a>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6 order-lg-2 text-center align-self-center"><img class="img-fluid" src="../assets/img/illustration/process-03.svg" alt="" width="400"></div>
          <div class="col-lg-6 border-lg-start border-lg-bottom py-lg-8 mt-4 mt-lg-0 mb-8 mb-lg-0">
            <div class="process-item ms-6 ms-sm-8 ms-lg-6"><span class="process-item-number">03</span>
              <h3>develop</h3>
              <p>With the blueprint &amp; design comps as our guide, the development team begins to create your website with the state of the earth tools. Our entire team works to add content, final design elements, review, &amp; test your website for quality.</p>
            </div>
          </div>
        </div>
        <div class="row pb-1">
          <div class="col-lg-6 border-lg-end text-center py-lg-8"><img class="img-fluid" src="../assets/img/illustration/process-04.svg" alt="" width="400"></div>
          <div class="col-lg-6 align-self-center mt-4 mt-lg-0 mt-lg-8">
            <div class="process-item process-item-last ms-6 ms-sm-8 ms-lg-6"><span class="process-item-number">04</span>
              <h3>deploy</h3>
              <p>After testing and review, we present your new website. Upon your approval, your website will be launched, promoted and optimized for search engines such as Google &amp; Bing.</p><a class="btn btn-outline-dark btn-sm mt-3" href="../pages/portfolio.html">See portfolio</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- end of .container-->
</section>

app/views/pages/host.html.erb
<div class="container-fluid hero-header py-5 mb-5">
  <div class="container py-5">
    <div class="row align-items-center">
      <div class="col-lg-6 intro-wrap">
        <h1>The next era of<br>
          unique outdoor experiences thrives<br>
          <a href="" class="typewrite" data-period="2000" data-type='[ "With you", "On Treepr", "Now" ]'><span class="wrap"></span></a>!
        </h1>
        <p>We are the all-in-one online solution that offers
          unique outdoor adventures for all nature lovers.<br>
          Create your experience now and get more clients.
        </p>
        <%= link_to "Get started", new_experience_path, class: "btn btn-flat" %>
      </div>
      <div class="col-lg-6 host-right">
        <%= image_tag "host_adventure.jpg" %>
      </div>
    </div>
  </div>
</div>




<script>
  var TxtType = function(el, toRotate, period) {
        this.toRotate = toRotate;
        this.el = el;
        this.loopNum = 0;
        this.period = parseInt(period, 10) || 2000;
        this.txt = '';
        this.tick();
        this.isDeleting = false;
    };

    TxtType.prototype.tick = function() {
        var i = this.loopNum % this.toRotate.length;
        var fullTxt = this.toRotate[i];

        if (this.isDeleting) {
        this.txt = fullTxt.substring(0, this.txt.length - 1);
        } else {
        this.txt = fullTxt.substring(0, this.txt.length + 1);
        }

        this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';

        var that = this;
        var delta = 200 - Math.random() * 100;

        if (this.isDeleting) { delta /= 2; }

        if (!this.isDeleting && this.txt === fullTxt) {
        delta = this.period;
        this.isDeleting = true;
        } else if (this.isDeleting && this.txt === '') {
        this.isDeleting = false;
        this.loopNum++;
        delta = 500;
        }

        setTimeout(function() {
        that.tick();
        }, delta);
    };

    window.onload = function() {
        var elements = document.getElementsByClassName('typewrite');
        for (var i=0; i<elements.length; i++) {
            var toRotate = elements[i].getAttribute('data-type');
            var period = elements[i].getAttribute('data-period');
            if (toRotate) {
              new TxtType(elements[i], JSON.parse(toRotate), period);
            }
        }
        // INJECT CSS
        var css = document.createElement("style");
        css.type = "text/css";
        css.innerHTML = ".typewrite > .wrap { border-right: 0.08em solid #fff}";
        document.body.appendChild(css);
    };
</script>

app/views/pages/my_experiences.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <h1><strong>My Listings<span style="color: #E67E22">.</span></strong></h1>
    <%= link_to "Host", new_experience_path, class: "btn btn-flat" %>
  </div>

  <br>
    <% if @experiences.any? %>
        <% @experiences.each do |experience| %>
          <div class="notification-header">

            <div class="notification-content">
              <p class="badge-progress">in progress</p>
              <h4><%= experience.name %></h4>
              <p><%= experience.address %></p>
            </div>

          </div>
          <div class="notification-footer">
            <a href="<%= overview_experience_path(experience) %>">Show <i class="fa-solid fa-eye"></i></a>
            <%= link_to "Delete",
              experience_path(experience),
              data: {"turbo_method": :delete, turbo_confirm: "Are you sure?"}
            %>
          </div>
          <br>

        <% end %>
      <% else %>
      <p>No activity listed</p>
    <% end %>

</div>

app/views/pages/standards.html.erb
<p>to file</p>

app/views/pages/why_hosting.html.erb
<p>to file</p>

app/views/shared/_experience_card.html.erb
<div class="card-experience">
   <%= cl_image_tag experience.cover.key, :transformation=>[
                {:width=>750, :crop=>"fit"}] %>
  <div class="card-experience-infos">
    <div>
      <h2><%= experience.name %></h2>
      <p>Short description here!</p>
    </div>
    <h2 class="card-experience-pricing">£99.99</h2>
    <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-experience-user avatar-bordered" />
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      Treepr<span style="color: #E67E22">.</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Inbox", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle test" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa-solid fa-campground"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Your profile", user_path(current_user), class: "dropdown-item" %>
              <% if current_user.experiences.any? %>
                <a class="dropdown-item" href="/my_experiences">My Experiences</a>
              <% else %>
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/my_experiences">Host an Experience</a>
              <% end -%>
              <a class="dropdown-item" href="/account">Account</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Help</a>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item"%>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Host", host_path, class: "btn btn-flat" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_onboarding_side_nav.html.erb
<div class="left-nav-crea h-100">

  <ul class="footer-links">
    <li class="d-flex justify-content-between align-items-start">
      <%= link_to "Your experience", overview_experience_path, class: "sidebar-link" %>
      <div><i class="fa-solid fa-circle-check mr-3 mb-3"></i></div>
    </li>
    <li class="d-flex justify-content-between align-items-start">
      <%= link_to "Description", description_experience_path, class: "sidebar-link" %>
      <% if @experience.description.blank? %>
        <div><i class="fa-solid fa-circle-notch mr-3 mb-3"></i></div>
      <% else %>
        <div><i class="fa-solid fa-circle-check mr-3 mb-3"></i></div>
      <% end %>
    </li>
    <li class="d-flex justify-content-between align-items-start">
      <%= link_to "Settings", settings_experience_path, class: "sidebar-link" %>
      <div><i class="fa-solid fa-circle-notch mr-3 mb-3"></i></div>
    </li>
    <li class="d-flex justify-content-between align-items-start">
      <%= link_to "Contact", contact_experience_path, class: "sidebar-link" %>
      <div><i class="fa-solid fa-circle-notch mr-3 mb-3"></i></div>
    </li>
    <li class="d-flex justify-content-between align-items-start">
      <%= link_to "photos", photos_experience_path, class: "sidebar-link" %>
      <div>
        <% if !@experience.cover.nil? %>
          <i class="fa-solid fa-circle-check mr-3 mb-3"></i>
        <% else %>
          <i class="fa-solid fa-circle-notch mr-3 mb-3"></i>
        <% end -%>
      </div>
    </li>
  </ul>

  <div class="btn btn-ghost">Submit</div>
</div>